<?php

return [
    'data' => [
        [
            'title' => 'ادمین مرکزی',
            'name' => 'administrator',
            'editable' => false,
            'permissions' => [
                'audit-log index',
                'audit-log detail',
                'audit-log delete',
                'system-log index',
                'system-log detail',
                'system-log delete',
                'account update',
                'account delete',
                'account detail',
                'account change-password',
                'account change-email',
                'user index',
                'user detail',
                'user create',
                'user update',
                'user delete',
                'role index',
                'role detail',
                'role create',
                'role update',
                'role delete',
                'estate-type create',
                'estate-type update',
                'estate-type delete',
                'estate-type index',
                'estate-type detail',
                'estate-document-type create',
                'estate-document-type update',
                'estate-document-type delete',
                'estate-document-type index',
                'estate-document-type detail',
                'estate-feature create',
                'estate-feature update',
                'estate-feature delete',
                'estate-feature index',
                'estate-feature detail',
                'estate-subscription create',
                'estate-subscription update',
                'estate-subscription delete',
                'estate-subscription index',
                'estate-subscription detail',
                'estate create',
                'estate update',
                'estate delete',
                'estate index',
                'estate detail',
            ],
        ],
        [
            'title' => 'ادمین',
            'name' => 'admin',
            'editable' => false,
            'permissions' => [
                'account update',
                'account delete',
                'account detail',
                'account change-password',
                'account change-email',
                'user index',
                'user detail',
                'user create',
                'user update',
                'user delete',
                'role index',
                'role detail',
                'role create',
                'role update',
                'role delete'
            ],
        ],
        [
            'title' => 'کاربر ساده',
            'name' => 'user',
            'editable' => true,
            'permissions' => [
                'account update',
                'account detail',
                'account change-password',
                'account change-email',
            ],
        ],
    ]
];
